"""empty message

Revision ID: 88013f50708d
Revises: 63c36fa94fce
Create Date: 2019-05-28 16:19:08.263451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88013f50708d'
down_revision = '63c36fa94fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dog', sa.Column('gender', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dog', 'gender')
    # ### end Alembic commands ###
