"""empty message

Revision ID: b573daef2c03
Revises: 88013f50708d
Create Date: 2019-05-30 02:55:00.516551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b573daef2c03'
down_revision = '88013f50708d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dog', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'dog', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
