"""empty message

Revision ID: dafd6a7e6d7c
Revises: 729aa7b5df9d
Create Date: 2019-05-25 18:04:24.499624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dafd6a7e6d7c'
down_revision = '729aa7b5df9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_name', sa.String(length=255), nullable=True),
    sa.Column('breed', sa.String(length=255), nullable=True),
    sa.Column('eye_color', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.String(length=255), nullable=True),
    sa.Column('fur_color', sa.String(length=255), nullable=True),
    sa.Column('fur_type', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dog')
    # ### end Alembic commands ###
